# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a5f34ac0646f434309fa58cba453c134fbaa26b458b4de450851e6064dadeebb59ef2ab05f6d83702abe987987ec721b6cad4b21c180db1a7f6e5fbbff5f0cd

test:
  secret_key_base: 3f76f4d42da2e99bdded3feac5ef300631dbfa939a322ac4e264efb108971b602fbb21c8a5f3dab9f73c14bd43ebf9c329fa8398b6bcba66ac0ac82739f5a6c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
